import { StockInfo } from './types';

export const VN30_LIST: StockInfo[] = [
  { ticker: 'ACB', name: 'Ngân hàng Á Châu', sector: 'Financials' },
  { ticker: 'BCM', name: 'Becamex IDC', sector: 'Real Estate' },
  { ticker: 'BID', name: 'BIDV', sector: 'Financials' },
  { ticker: 'BVH', name: 'Tập đoàn Bảo Việt', sector: 'Financials' },
  { ticker: 'CTG', name: 'VietinBank', sector: 'Financials' },
  { ticker: 'FPT', name: 'FPT Corp', sector: 'Technology' },
  { ticker: 'GAS', name: 'PV Gas', sector: 'Utilities' },
  { ticker: 'GVR', name: 'Tập đoàn Cao su', sector: 'Materials' },
  { ticker: 'HDB', name: 'HDBank', sector: 'Financials' },
  { ticker: 'HPG', name: 'Hòa Phát', sector: 'Materials' },
  { ticker: 'MBB', name: 'MBBank', sector: 'Financials' },
  { ticker: 'MSN', name: 'Masan Group', sector: 'Consumer Staples' },
  { ticker: 'MWG', name: 'Thế Giới Di Động', sector: 'Consumer Discretionary' },
  { ticker: 'PLX', name: 'Petrolimex', sector: 'Energy' },
  { ticker: 'POW', name: 'PV Power', sector: 'Utilities' },
  { ticker: 'SAB', name: 'Sabeco', sector: 'Consumer Staples' },
  { ticker: 'SHB', name: 'SHB Bank', sector: 'Financials' },
  { ticker: 'SSB', name: 'SeABank', sector: 'Financials' },
  { ticker: 'SSI', name: 'Chứng khoán SSI', sector: 'Financials' },
  { ticker: 'STB', name: 'Sacombank', sector: 'Financials' },
  { ticker: 'TCB', name: 'Techcombank', sector: 'Financials' },
  { ticker: 'TPB', name: 'TPBank', sector: 'Financials' },
  { ticker: 'VCB', name: 'Vietcombank', sector: 'Financials' },
  { ticker: 'VHM', name: 'Vinhomes', sector: 'Real Estate' },
  { ticker: 'VIB', name: 'VIB Bank', sector: 'Financials' },
  { ticker: 'VIC', name: 'Vingroup', sector: 'Real Estate' },
  { ticker: 'VJC', name: 'Vietjet Air', sector: 'Industrials' },
  { ticker: 'VNM', name: 'Vinamilk', sector: 'Consumer Staples' },
  { ticker: 'VPB', name: 'VPBank', sector: 'Financials' },
  { ticker: 'VRE', name: 'Vincom Retail', sector: 'Real Estate' },
];